GET localhost:8081/projects/tasks/2

###

GET localhost:8081/projects/1/tasks/list

###

GET localhost:8081/projects/1/tasks/list/simple


###

POST localhost:8081/projects/1/tasks/upload/test1
Content-Type: application/json

{
    "userId": "test1",
  "taskTitle": "title1",
  "taskContent": "content1"
}

###

PUT localhost:8081/projects/tasks/4/update/test1
Content-Type: application/json

{
    "taskTitle": "title12",
  "taskContent": "content11"
}

###

DELETE localhost:8081/projects/tasks/4/delete/test1
